name = "RationalFunctionApproximation"
uuid = "c92886a3-cb30-4e18-b84f-372dde475ecc"
authors = ["Toby Driscoll <driscoll@udel.edu> and contributors"]
version = "0.1.4"

[deps]
ComplexRegions = "c64915e2-6c82-11e9-38e9-1f159a780463"
ComplexValues = "41a84b80-6cf2-11e9-379d-9df124847946"
GenericLinearAlgebra = "14197337-ba66-59df-a3e3-ca00e7dcff7a"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
PyFormattedStrings = "5f89f4a4-a228-4886-b223-c468a82ed5b9"

[weakdeps]
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[extensions]
RFAMakieExt = "Makie"
RFAPlotsExt = "Plots"
RFAPythonCallExt = "PythonCall"

[compat]
ComplexRegions = "0.2, 0.3"
ComplexValues = "0.3"
GenericLinearAlgebra = "0.3"
PyFormattedStrings = "0.1"
julia = "1.9"

[extras]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ComplexRegions = "c64915e2-6c82-11e9-38e9-1f159a780463"
DoubleFloats = "497a8b3b-efae-58df-a0af-a86822472b78"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
docs = ["CairoMakie"]
test = ["Test", "LinearAlgebra", "ComplexRegions", "DoubleFloats"]
