name = "RationalFunctionApproximation"
uuid = "c92886a3-cb30-4e18-b84f-372dde475ecc"
authors = ["Toby Driscoll <driscoll@udel.edu> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
